<script setup lang="ts">
/**
 * App Chart configuration Tab
 * use PanelEditorV2 Make visual edits
 * Data format：{ version: "v2", web: { config: {...} }, app: { config: {...} } }
 * save to web_chart_config field app part
 */

import { ref, inject, computed } from 'vue'
import type { Ref } from 'vue'
import { NSpin, NEmpty, NAlert } from 'naive-ui'
import PanelEditorV2 from '@/components/visual-editor/PanelEditorV2.vue'
import { putTemplat } from '@/service/api/system-data'
import { $t } from '@/locales'

const templateData = inject<Ref<any>>('templateData')!

const saving = ref(false)

// 🔥 Editor configuration status
const editorConfig = ref<{ widgets: any[]; config: any } | undefined>()

// 🔥 Is it an old version of data?（No v2 Format）
const isLegacyData = ref(false)

// Visual Editor need a unique panelId
const panelId = computed(() => {
  return templateData.value?.id ? `template-${templateData.value.id}-app` : ''
})

/**
 * 🔥 parse web_chart_config and extract App Configuration
 */
const parseAppChartConfig = () => {
  if (!templateData.value?.web_chart_config) {
    // No configuration，Use empty configuration
    editorConfig.value = {
      widgets: [],
      config: { gridConfig: {}, canvasConfig: {} }
    }
    return
  }

  try {
    const parsed = JSON.parse(templateData.value.web_chart_config)

    // Check if it is v2 Format
    if (parsed.version === 'v2' && parsed.app?.config) {
      // v2 Format，extract app.config
      editorConfig.value = parsed.app.config
      isLegacyData.value = false
    } else {
      // Legacy data or other formats
      isLegacyData.value = true
      editorConfig.value = undefined
    }
  } catch (e) {
    console.error('❌ parse web_chart_config fail:', e)
    // Parsing failed，Use empty configuration
    editorConfig.value = {
      widgets: [],
      config: { gridConfig: {}, canvasConfig: {} }
    }
  }
}

// Parse configuration during initialization
parseAppChartConfig()

/**
 * 🔥 Custom save processing function
 * save to web_chart_config of app part
 */
const handleCustomSave = async (editorState: any) => {
  if (saving.value) return

  saving.value = true
  try {
    // 1. Read existing configuration（reserve web part）
    let existingConfig: any = { version: 'v2', web: {}, app: {} }
    if (templateData.value?.web_chart_config) {
      try {
        const parsed = JSON.parse(templateData.value.web_chart_config)
        if (parsed.version === 'v2') {
          existingConfig = parsed
        }
      } catch (e) {
        // Legacy data or parsing failure，neglect
      }
    }

    // 2. renew app part（Save the complete data generated by the Kanban board）
    existingConfig.app = {
      config: editorState, // editorState yes {widgets: [...], config: {...}}
      updatedAt: new Date().toISOString()
    }

    // 3. save to web_chart_config Field
    const response = await putTemplat({
      ...templateData.value,
      web_chart_config: JSON.stringify(existingConfig)
    })

    if (response.error) {
      throw new Error(response.error)
    }

    // renew templateData
    if (templateData.value) {
      templateData.value.web_chart_config = JSON.stringify(existingConfig)
    }
  } finally {
    saving.value = false
  }
}

/**
 * Listen for save success events
 */
const handleSaveSuccess = () => {
  window.$message?.success($t('common.saveSuccess'))
}

/**
 * Listen for save failure events
 */
const handleSaveError = (error: any) => {
  console.error('save App Chart configuration failed:', error)
  window.$message?.error($t('common.saveFailed'))
}

/**
 * 🔥 Recreate configuration
 */
const handleRecreate = () => {
  isLegacyData.value = false
  editorConfig.value = {
    widgets: [],
    config: { gridConfig: {}, canvasConfig: {} }
  }
}
</script>

<template>
  <div class="tab-content">
    <NSpin :show="saving">
      <!-- Old version data tips -->
      <div v-if="isLegacyData" class="legacy-data-warning">
        <NAlert type="warning" :title="$t('device_template.legacyDataDetected') || 'Legacy data detected'" closable>
          <template #default>
            {{ $t('device_template.legacyDataMessage') || 'Current configuration is in legacy format，Cannot edit directly。Please recreate the configuration。' }}
          </template>
          <template #action>
            <n-button size="small" @click="handleRecreate">
              {{ $t('device_template.recreate') || 'Recreate' }}
            </n-button>
          </template>
        </NAlert>
      </div>

      <!-- panelId Prompt when empty -->
      <div v-else-if="!panelId" class="empty-state">
        <n-empty :description="$t('common.loadError')" />
      </div>

      <!-- normal editor -->
      <div v-else-if="editorConfig" class="editor-wrapper">
        <PanelEditorV2
          :key="`app-${panelId}`"
          :panel-id="panelId"
          :initial-config="editorConfig"
          :custom-save-handler="handleCustomSave"
          :show-toolbar="true"
          :show-page-header="false"
          mode="template"
          @save-success="handleSaveSuccess"
          @save-error="handleSaveError"
        />
      </div>
    </NSpin>
  </div>
</template>

<style scoped lang="scss">
.tab-content {
  padding: 0;
  min-height: 600px;
  position: relative;
}

.legacy-data-warning {
  padding: 16px;
}

.editor-wrapper {
  width: 100%;
  height: 100%;
  min-height: 600px;
}

.empty-state {
  display: flex;
  align-items: center;
  justify-content: center;
  min-height: 400px;
}
</style>
