/**
 * Equipment parameter group type definition
 * Used to manage related parameters generated by device selection
 */

/**
 * Device parameter group source type
 */
export type DeviceParameterSourceType =
  | 'device-id' // equipmentIDselector：only generatedeviceIdparameter
  | 'device-metric' // Indicator selector：producedeviceId + metricparameter
  | 'telemetry' // telemetry selector：Flexible generation of multiple parameters

/**
 * Device information
 */
export interface DeviceInfo {
  deviceId: string
  deviceName: string
  deviceType: string
  deviceModel?: string
}

/**
 * Device indicator information
 */
export interface DeviceMetric {
  metricKey: string
  metricLabel: string
  metricType: 'string' | 'number' | 'boolean' | 'json'
  unit?: string
  description?: string
}

/**
 * Telemetry configuration（Reserved for future complex patterns）
 */
export interface TelemetryConfig {
  deviceId: string
  metricTypes: string[] // like：['realtime', 'history']
  selectedMetrics: string[] // Selected indicatorskeys
  timeParameters: string[] // Time related parameters，like：['startTime', 'endTime']
  customParameters?: Record<string, any> // Custom parameters
}

/**
 * Device selection configuration（Used to echo when editing）
 */
export interface DeviceSelectionConfig {
  sourceType: DeviceParameterSourceType
  selectedDevice: DeviceInfo
  selectedMetric?: DeviceMetric // Used in indicator mode
  telemetryConfig?: TelemetryConfig // Used in telemetry mode
  timestamp: number // Select timestamp
}

/**
 * Parameter's role in the group
 */
export type ParameterRole = 'primary' | 'secondary' | 'derived' | 'optional'

/**
 * Parameter group information
 */
export interface DeviceParameterGroup {
  /** Parameter group unique identifier */
  groupId: string

  /** Parameter group source type */
  sourceType: DeviceParameterSourceType

  /** Original selection configuration（Used to echo when editing） */
  sourceConfig: DeviceSelectionConfig

  /** associated parameterskeylist */
  relatedParams: string[]

  /** Dependencies between parameters */
  dependencies: {
    [paramKey: string]: {
      dependsOn: string[] // What parameters does it depend on
      affects: string[] // Which parameters are affected?
      role: ParameterRole // parameter role
    }
  }

  /** Parameter group creation time */
  createdAt: number

  /** Parameter group last updated time */
  updatedAt: number
}

/**
 * Enhanced parameter types（Extend the originalEnhancedParameter）
 */
export interface DeviceParameterGroupInfo {
  /** Parameter group to which it belongsID */
  groupId: string

  /** Role in the group */
  role: ParameterRole

  /** Whether it is a derived parameter（Calculated from other parameters） */
  isDerived: boolean

  /** Source type of parameter group */
  sourceType: DeviceParameterSourceType
}

/**
 * Device selector mode configuration
 */
export interface DeviceSelectionMode {
  /** Schema type */
  mode: DeviceParameterSourceType

  /** Schema title */
  title: string

  /** Schema description */
  description: string

  /** mode icon */
  icon: string

  /** Whether to enable */
  enabled: boolean

  /** The number of parameters expected to be generated */
  expectedParams: number
}

/**
 * Device selection results
 */
export interface DeviceSelectionResult {
  /** Generated parameter list */
  parameters: Array<{
    key: string
    value: any
    dataType: string
    description: string
    role: ParameterRole
  }>

  /** Parameter group information */
  groupInfo: DeviceParameterGroup

  /** Select configuration */
  selectionConfig: DeviceSelectionConfig
}
