/**
 * Simplify data source system type definition
 * Simplified design based on learning from existing systems
 */

// ========== Component data requirement type ==========

/**
 * Component Data Requirements Statement - andCard2.1Fully compatible
 * supportCard2.1 ComponentDefinitionin staticParams and dataSources
 */
export interface ComponentDataRequirement {
  /** componentsID */
  componentId: string
  /** Component name */
  componentName: string
  /** Static parameter requirement declaration - andCard2.1 StaticParamRequirementcorrespond */
  staticParams?: StaticParamRequirement[]
  /** Data source requirement statement - andCard2.1 DataSourceRequirementcorrespond */
  dataSources: DataSourceRequirement[]
}

/**
 * Static parameter requirement definition - andCard2.1completely consistent
 */
export interface StaticParamRequirement {
  /** Parameter unique identifier */
  key: string
  /** Parameter name */
  name: string
  /** Parameter type */
  type: 'string' | 'number' | 'boolean' | 'object' | 'array'
  /** Parameter description */
  description: string
  /** default value */
  defaultValue?: any
  /** Is it required? */
  required?: boolean
  /** Parameter validation rules */
  validation?: {
    min?: number
    max?: number
    pattern?: string
    options?: Array<{ label: string; value: any }>
  }
  /** UI Rendering tips */
  ui?: {
    component?: 'input' | 'select' | 'number' | 'switch' | 'textarea' | 'color' | 'slider'
    placeholder?: string
    label?: string
    group?: string
  }
}

/**
 * Data source requirement statement - andCard2.1Fully compatible version
 */
export interface DataSourceRequirement {
  /** Data source unique identifier - andCard2.1 keycorrespond */
  key: string
  /** Data source name */
  name: string
  /** Data source description */
  description: string
  /** Supported data source types - andCard2.1Alignment */
  supportedTypes: Array<'static' | 'api' | 'websocket' | 'mqtt' | 'database'>
  /** Field mapping rules - andCard2.1 fieldMappingscompatible */
  fieldMappings: Record<
    string,
    {
      /** Target field name */
      targetField: string
      /** Field type */
      type: 'value' | 'object' | 'array'
      /** Is it required? */
      required: boolean
      /** default value */
      defaultValue?: any
      /** data conversion function */
      transform?: string
    }
  >
  /** Is it required? */
  required?: boolean

  // ==== backward compatibility fields - Support original simplified format ====
  /** data structure type - backward compatible */
  structureType?: 'object' | 'array'
  /** Field requirements - backward compatible */
  fields?: FieldRequirement[]
  /** data sourceID - backward compatible */
  id?: string
}

/**
 * Field requirement statement - andCard2.1Compatible extended version
 */
export interface FieldRequirement {
  /** Field name */
  name: string
  /** Field type - Extended supportCard2.1type system */
  type: 'string' | 'number' | 'boolean' | 'any' | 'object' | 'array'
  /** value type - Used to further subdivide types */
  valueType?: 'number' | 'string' | 'boolean' | 'any'
  /** Is it required? */
  required: boolean
  /** Field description */
  description: string
  /** Example value */
  example?: any
  /** default value - andCard2.1 StaticParamRequirementcompatible */
  defaultValue?: any
  /** Nested structure definition - Supports complex objects and arrays */
  structure?: DataSourceRequirement
  /** Validation rules - andCard2.1Compatible authentication configurations */
  validation?: {
    min?: number
    max?: number
    pattern?: string
    options?: Array<{ label: string; value: any }>
  }
  /** UIRendering tips - supportCard2.1ofUIConfiguration */
  ui?: {
    component?: 'input' | 'select' | 'number' | 'switch' | 'textarea' | 'color' | 'slider'
    placeholder?: string
    label?: string
    group?: string
  }
}

// ========== Data source configuration type ==========

/**
 * Simplified data source configuration - Output to external systems for use
 * This is the standard configuration format generated by the configurator
 */
export interface SimpleDataSourceConfig {
  /** ConfigurationID */
  id: string
  /** componentsID */
  componentId: string
  /** Data source definition list */
  dataSources: DataSourceDefinition[]
  /** Trigger configuration - ReuseCard2.1excellent design */
  triggers: TriggerConfig[]
  /** Whether to enable */
  enabled: boolean
}

/**
 * Data source definition
 */
export interface DataSourceDefinition {
  /** data sourceID */
  id: string
  /** Data source type */
  type: 'static' | 'api' | 'websocket' | 'script'
  /** Data source configuration */
  config: any
  /** Field mapping - learn fromvisual-editormapping mechanism */
  fieldMapping?: { [targetField: string]: string }
}

/**
 * Trigger configuration - ReuseCard2.1trigger system
 */
export interface TriggerConfig {
  /** Trigger type */
  type: 'timer' | 'websocket' | 'event' | 'manual'
  /** Trigger configuration */
  config: TriggerConfigData
}

/**
 * Trigger configuration data
 */
export interface TriggerConfigData {
  // Timer configuration
  interval?: number
  immediate?: boolean

  // WebSocketConfiguration
  url?: string
  protocols?: string[]

  // event configuration
  eventName?: string
  target?: EventTarget
}

// ========== Component data type ==========

/**
 * The final data format received by the component
 * This is the standard format for executor output to components
 */
export interface ComponentData {
  [dataSourceId: string]: {
    /** Data source type */
    type: string
    /** parsed data */
    data: any
    /** Last updated */
    lastUpdated?: number
    /** metadata */
    metadata?: any
  }
}

/**
 * Standard componentsProps - The interface used by the new component
 */
export interface StandardComponentProps {
  /** Data source configuration */
  dataSourceConfig?: ComponentData
}

// ========== User input type ==========

/**
 * User data source input
 * Data entered by the user in the configuration interface
 */
export interface UserDataSourceInput {
  /** data sourceID */
  dataSourceId: string
  /** Data source type */
  type: 'static' | 'api' | 'websocket' | 'script'
  /** User input configuration */
  config: DataSourceUserConfig
}

/**
 * Data source user configuration
 */
export type DataSourceUserConfig =
  | StaticDataSourceConfig
  | ApiDataSourceConfig
  | WebSocketDataSourceConfig
  | ScriptDataSourceConfig

/**
 * Static data source configuration
 */
export interface StaticDataSourceConfig {
  /** static data - JSONstring or object */
  data: any
}

/**
 * APIData source configuration
 */
export interface ApiDataSourceConfig {
  /** APIaddress */
  url: string
  /** HTTPmethod */
  method: 'GET' | 'POST' | 'PUT' | 'DELETE'
  /** Request header */
  headers?: Record<string, string>
  /** Request body */
  body?: any
  /** timeout */
  timeout?: number
}

/**
 * WebSocketData source configuration
 */
export interface WebSocketDataSourceConfig {
  /** WebSocketaddress */
  url: string
  /** protocol */
  protocols?: string[]
  /** reconnection interval */
  reconnectInterval?: number
}

/**
 * Script data source configuration
 */
export interface ScriptDataSourceConfig {
  /** JavaScriptscript code */
  script: string
  /** script context */
  context?: Record<string, any>
}

// ========== Execution result type ==========

/**
 * Data execution results
 */
export interface ExecutionResult {
  /** Is it successful? */
  success: boolean
  /** Data content */
  data?: ComponentData
  /** error message */
  error?: string
  /** Execution time（millisecond） */
  executionTime: number
  /** Timestamp */
  timestamp: number
}

/**
 * Field mapping preview results
 */
export interface MappingPreviewResult {
  /** target field */
  targetField: string
  /** source path */
  sourcePath: string
  /** mapped value */
  mappedValue: any
  /** Is it successful? */
  success: boolean
  /** error message */
  error?: string
}

// ========== Validation result type ==========

/**
 * Configuration verification results
 */
export interface ValidationResult {
  /** Is it valid? */
  valid: boolean
  /** error message */
  errors: string[]
  /** warning message */
  warnings: string[]
}

// ========== Compatibility type ==========

/**
 * Visual Editor Compatible formats
 */
export interface VisualEditorCompatibleProps {
  widgetConfiguration?: {
    dataSource: {
      config: {
        dataSourceBindings: {
          [dataSourceId: string]: {
            rawData: string
          }
        }
      }
    }
  }
}

/**
 * Card2.1 Compatible formats
 */
export interface Card21CompatibleProps {
  rawDataSources?: {
    dataSourceBindings: {
      [dataSourceId: string]: {
        rawData: string
      }
    }
  }
}

// ========== Tool type ==========

/**
 * data source type union type
 */
export type DataSourceType = 'static' | 'api' | 'websocket' | 'script'

/**
 * field type union type - Extended supportCard2.1compatibility
 */
export type FieldType = 'string' | 'number' | 'boolean' | 'any' | 'object' | 'array'

/**
 * field value type union type - Used to subdivide base types
 */
export type FieldValueType = 'string' | 'number' | 'boolean' | 'any'

/**
 * trigger type union type
 */
export type TriggerType = 'timer' | 'websocket' | 'event' | 'manual'

/**
 * Component type
 */
export type ComponentType = 'visual-editor' | 'card2.1' | 'standard'

/**
 * Card2.1Component requirement statement format - direct quoteCard2.1type
 */
export interface Card2ComponentRequirement {
  /** Static parameter requirement declaration */
  staticParams?: any[]
  /** Data source requirement statement */
  dataSources?: any[]
}

// ========== constant definition ==========

/**
 * System constants
 */
export const SIMPLE_DATA_SOURCE_CONSTANTS = {
  /** Maximum number of data sources */
  MAX_DATA_SOURCES: 5,

  /** Default trigger interval */
  DEFAULT_TRIGGER_INTERVAL: 30000,

  /** Default timeout */
  DEFAULT_TIMEOUT: 10000,

  /** Configuration version */
  CONFIG_VERSION: '2.0.0'
} as const

// ========== Card2.1Compatible type conversion tools ==========

/**
 * Card2.1 StaticParamRequirementconversion tool
 */
export interface Card2StaticParamCompatibility {
  /**
   * WillCard2.1 StaticParamRequirementConvert to data source systemStaticParamRequirement
   */
  fromCard2StaticParam(card2Param: any): StaticParamRequirement

  /**
   * data source systemStaticParamRequirementConvert toCard2.1Format
   */
  toCard2StaticParam(staticParam: StaticParamRequirement): any
}

/**
 * Card2.1 DataSourceRequirementconversion tool
 */
export interface Card2DataSourceCompatibility {
  /**
   * WillCard2.1 DataSourceRequirementConvert to data source system format
   */
  fromCard2DataSource(card2DataSource: any): DataSourceRequirement

  /**
   * Convert data source system format toCard2.1 DataSourceRequirement
   */
  toCard2DataSource(dataSource: DataSourceRequirement): any
}

/**
 * Component Data Requirements Conversion Tool
 */
export interface ComponentRequirementCompatibility {
  /**
   * fromCard2.1 ComponentDefinitionExtract data requirements
   */
  extractFromCard2Component(componentDef: any): ComponentDataRequirement

  /**
   * WillComponentDataRequirementConvert toCard2.1Compatible formats
   */
  adaptToCard2Component(requirement: ComponentDataRequirement): {
    staticParams?: any[]
    dataSources?: any[]
  }
}

/**
 * Field type mapping table - Card2.1Type mapping to and from the data source system
 */
export const FIELD_TYPE_MAPPING = {
  // Card2.1 -> Data source system
  card2ToDataSource: {
    value: 'any' as FieldType,
    object: 'object' as FieldType,
    array: 'array' as FieldType,
    string: 'string' as FieldType,
    number: 'number' as FieldType,
    boolean: 'boolean' as FieldType
  },
  // Data source system -> Card2.1
  dataSourceToCard2: {
    string: 'value',
    number: 'value',
    boolean: 'value',
    any: 'value',
    object: 'object',
    array: 'array'
  }
} as const
